version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8090
    volumes:
      - .:/app
    ports:
      - "8090:8090"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=deepgis_xr.settings
    depends_on:
      - redis
      - celery

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A deepgis_xr worker -l INFO
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=deepgis_xr.settings
    depends_on:
      - redis 