version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "
        python3.9 manage.py makemigrations &&
        python3.9 manage.py migrate auth &&
        python3.9 manage.py migrate contenttypes &&
        python3.9 manage.py migrate admin &&
        python3.9 manage.py migrate sessions &&
        python3.9 manage.py migrate deepgis_auth &&
        python3.9 manage.py migrate &&
        python3.9 manage.py collectstatic --noinput &&
        python3.9 manage.py runserver 0.0.0.0:8060"
    volumes:
      - .:/app
      - ./static:/app/static
      - /mnt/2tbc2000mx500ssd/deepgis/deepgis_rocks/static-root/C3_mask_v3.tif:/app/static/C3_mask_v3.tif
      - /mnt/2tbc2000mx500ssd/deepgis/deepgis_rocks/static-root/pb-rock.stl:/app/static/pb-rock.stl
      - /mnt/2tbc2000mx500ssd/deepgis/deepgis_rocks/static-root/C3.tif:/app/static/C3.tif
      - /mnt/2tbc2000mx500ssd/deepgis/deepgis_rocks/rocks-coord-list.csv:/app/static/rocks-coord-list.csv
      - /mnt/2tbc2000mx500ssd/deepgis/deepgis_rocks_static_serving_nginx/static/rock-tiles:/app/static/rock-tiles
      - media_volume:/app/media
    ports:
      - "8060:8060"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=deepgis_xr.settings
      - POSTGRES_DB=gis_db
      - POSTGRES_USER=gis_user
      - POSTGRES_PASSWORD=gis_password
      - POSTGRES_HOST=db
      - REDIS_URL=redis://redis:6379/0
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgis/postgis:13-3.3
    environment:
      - POSTGRES_DB=gis_db
      - POSTGRES_USER=gis_user
      - POSTGRES_PASSWORD=gis_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gis_user -d gis_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    expose:
      - 6379
    command: redis-server --appendonly yes

  celery:
    build: .
    command: celery -A deepgis_xr worker -l INFO
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=deepgis_xr.settings
      - REDIS_URL=redis://redis:6379/0
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
    depends_on:
      - redis
      - db

  tileserver:
    image: maptiler/tileserver-gl
    ports:
      - "8091:80"
    volumes:
      - ./static/rock-tiles/mbtiles:/data/mbtiles
      - ./static/rock-tiles/styles:/data/styles
      - ./static/rock-tiles/config.json:/data/config.json
    environment:
      - CORS_ENABLED=true
      - TILESERVER_GL_DATA_PATH=/data
    command: ["-c", "/data/config.json", "-p", "80", "--verbose"]
    restart: unless-stopped

volumes:
  postgres_data:
  media_volume: 