version: '3.9'

services:
  web:
    build:
      context: .
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=deepgis_xr.settings
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8060:8090"
    command: >
      bash -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8090
      "

  tileserver:
    image: maptiler/tileserver-gl
    ports:
      - "8091:80"
    volumes:
      - ./data:/data
    environment:
      - CORS_ENABLED=true
      - TILESERVER_GL_DATA_PATH=/data
    command: ["-p", "80", "--verbose"]

volumes:
  media_volume: 