version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "
        python3.9 manage.py makemigrations &&
        python3.9 manage.py migrate auth &&
        python3.9 manage.py migrate contenttypes &&
        python3.9 manage.py migrate admin &&
        python3.9 manage.py migrate sessions &&
        python3.9 manage.py migrate deepgis_auth &&
        python3.9 manage.py migrate &&
        python3.9 manage.py runserver 0.0.0.0:8090
      "
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8090
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=deepgis_xr.settings
      - POSTGRES_DB=gis_db
      - POSTGRES_USER=gis_user
      - POSTGRES_PASSWORD=gis_password
      - POSTGRES_HOST=db
      - REDIS_URL=redis://redis:6379/0
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx/dreamslab.deepgis.org.conf:/etc/nginx/conf.d/default.conf
      - ./deepgis_xr/static:/app/deepgis_xr/static
      - media_volume:/app/media
    ports:
      - "8090:80"
    depends_on:
      - web

  db:
    image: postgis/postgis:13-3.3
    environment:
      - POSTGRES_DB=gis_db
      - POSTGRES_USER=gis_user
      - POSTGRES_PASSWORD=gis_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gis_user -d gis_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    expose:
      - 6379
    command: redis-server --appendonly yes

  celery:
    build: .
    command: celery -A deepgis_xr worker -l INFO
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=deepgis_xr.settings
      - REDIS_URL=redis://redis:6379/0
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume: 