# Generated by Django 3.2.24 on 2025-11-26 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance'), ('LOST', 'Lost Signal'), ('EMERGENCY', 'Emergency')], default='INACTIVE', max_length=20)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True)),
                ('current_altitude', models.FloatField(blank=True, help_text='Altitude in meters', null=True)),
                ('current_heading', models.FloatField(blank=True, help_text='Heading in degrees (0-360)', null=True)),
                ('current_speed', models.FloatField(blank=True, help_text='Speed in m/s', null=True)),
                ('mission_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_icon', models.CharField(blank=True, max_length=10, null=True)),
                ('show_trail', models.BooleanField(default=True)),
                ('trail_length', models.PositiveIntegerField(default=100, help_text='Number of trail points to show')),
                ('max_speed', models.FloatField(blank=True, help_text='Maximum speed in m/s', null=True)),
                ('max_altitude', models.FloatField(blank=True, help_text='Maximum altitude in meters', null=True)),
                ('battery_level', models.FloatField(blank=True, help_text='Battery level 0-100%', null=True)),
                ('custom_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.color')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_update'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('DRONE', 'Drone/UAV'), ('GROUND', 'Ground Vehicle'), ('MARINE', 'Marine Vehicle'), ('AIRCRAFT', 'Aircraft'), ('SATELLITE', 'Satellite'), ('PERSON', 'Person/Personnel'), ('ROBOT', 'Robot'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('icon_url', models.URLField(blank=True, max_length=500, null=True)),
                ('icon_symbol', models.CharField(default='📍', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.color')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=17)),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in meters', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Heading in degrees (0-360)', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in m/s', null=True)),
                ('vertical_speed', models.FloatField(blank=True, help_text='Vertical speed in m/s', null=True)),
                ('gps_accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('satellite_count', models.PositiveIntegerField(blank=True, null=True)),
                ('battery_level', models.FloatField(blank=True, help_text='Battery level 0-100%', null=True)),
                ('signal_strength', models.FloatField(blank=True, help_text='Signal strength in dBm', null=True)),
                ('sensor_data', models.JSONField(blank=True, default=dict, help_text='Additional sensor readings')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VehicleGeofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('geofence_type', models.CharField(choices=[('INCLUSION', 'Inclusion Zone'), ('EXCLUSION', 'Exclusion Zone'), ('WARNING', 'Warning Zone'), ('LANDING', 'Landing Zone'), ('TAKEOFF', 'Takeoff Zone')], max_length=20)),
                ('geometry', models.TextField(help_text='GeoJSON geometry definition')),
                ('min_altitude', models.FloatField(blank=True, help_text='Minimum altitude in meters', null=True)),
                ('max_altitude', models.FloatField(blank=True, help_text='Maximum altitude in meters', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicles', models.ManyToManyField(blank=True, related_name='geofences', to='core.Vehicle')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('GEOFENCE', 'Geofence Violation'), ('LOW_BATTERY', 'Low Battery'), ('SIGNAL_LOST', 'Signal Lost'), ('SPEED_LIMIT', 'Speed Limit Exceeded'), ('ALTITUDE_LIMIT', 'Altitude Limit Exceeded'), ('EMERGENCY', 'Emergency'), ('MAINTENANCE', 'Maintenance Required'), ('CUSTOM', 'Custom Alert')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicletype'),
        ),
        migrations.AddIndex(
            model_name='vehicleposition',
            index=models.Index(fields=['vehicle', '-timestamp'], name='core_vehicl_vehicle_fd938c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleposition',
            index=models.Index(fields=['latitude', 'longitude'], name='core_vehicl_latitud_de21b4_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleposition',
            index=models.Index(fields=['timestamp'], name='core_vehicl_timesta_ce3e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclealert',
            index=models.Index(fields=['vehicle', '-created_at'], name='core_vehicl_vehicle_a4ed4b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclealert',
            index=models.Index(fields=['alert_type'], name='core_vehicl_alert_t_05c92e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclealert',
            index=models.Index(fields=['severity'], name='core_vehicl_severit_1f93b4_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclealert',
            index=models.Index(fields=['is_acknowledged'], name='core_vehicl_is_ackn_5aafe2_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_id'], name='core_vehicl_vehicle_310bd1_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status'], name='core_vehicl_status_187554_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['last_update'], name='core_vehicl_last_up_fd7eae_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['current_latitude', 'current_longitude'], name='core_vehicl_current_2c4a31_idx'),
        ),
    ]
