# Generated by Django 3.2.24 on 2025-11-29 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20251126_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Training'), ('training', 'Training in Progress'), ('completed', 'Training Completed')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Dataset',
                'verbose_name_plural': 'Training Datasets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_prediction_id', models.CharField(blank=True, help_text='Original Mask2Former session_id', max_length=200, null=True)),
                ('corrections_made', models.JSONField(blank=True, default=dict, help_text='Track what corrections were made')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_labels', to='core.trainingdataset')),
                ('image_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_datasets', to='core.imagelabel')),
            ],
            options={
                'verbose_name': 'Training Label',
                'verbose_name_plural': 'Training Labels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Model name (e.g., 'Custom Mask2Former')", max_length=200)),
                ('version', models.CharField(help_text="Version string (e.g., '1.0', '2.1')", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('base_model', models.CharField(default='mask2former_coco', help_text='Base model used for fine-tuning', max_length=100)),
                ('model_path', models.CharField(help_text='Path to trained model .pth file', max_length=500)),
                ('config_path', models.CharField(blank=True, help_text='Path to model config file', max_length=500)),
                ('training_loss', models.FloatField(blank=True, null=True)),
                ('validation_loss', models.FloatField(blank=True, null=True)),
                ('mAP_score', models.FloatField(blank=True, help_text='Mean Average Precision', null=True)),
                ('status', models.CharField(choices=[('training', 'Training'), ('completed', 'Completed'), ('deployed', 'Deployed'), ('archived', 'Archived')], default='training', max_length=20)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('trained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_models', to=settings.AUTH_USER_MODEL)),
                ('training_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_versions', to='core.trainingdataset')),
            ],
            options={
                'verbose_name': 'Model Version',
                'verbose_name_plural': 'Model Versions',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.AddIndex(
            model_name='traininglabel',
            index=models.Index(fields=['dataset', '-created_at'], name='core_traini_dataset_9f266d_idx'),
        ),
        migrations.AddIndex(
            model_name='traininglabel',
            index=models.Index(fields=['source_prediction_id'], name='core_traini_source__840929_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='traininglabel',
            unique_together={('dataset', 'image_label')},
        ),
        migrations.AddIndex(
            model_name='modelversion',
            index=models.Index(fields=['name', 'version'], name='core_modelv_name_b53bee_idx'),
        ),
        migrations.AddIndex(
            model_name='modelversion',
            index=models.Index(fields=['status'], name='core_modelv_status_8e81ed_idx'),
        ),
        migrations.AddIndex(
            model_name='modelversion',
            index=models.Index(fields=['-trained_at'], name='core_modelv_trained_24f97c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modelversion',
            unique_together={('name', 'version')},
        ),
    ]
