# Generated by Django 3.2.24 on 2025-11-29 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20251129_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('mission_type', models.CharField(choices=[('SURVEY', 'Survey'), ('PATROL', 'Patrol'), ('DATA_CAPTURE', 'Data Capture'), ('INSPECTION', 'Inspection'), ('MAPPING', 'Mapping'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('UPLOADED', 'Uploaded to Vehicle'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('waypoints', models.JSONField(default=list, help_text='GeoJSON FeatureCollection of waypoints')),
                ('default_altitude', models.FloatField(default=50.0, help_text='Default altitude in meters')),
                ('default_speed', models.FloatField(blank=True, help_text='Default speed in m/s', null=True)),
                ('return_to_home', models.BooleanField(default=True, help_text='Return to home after mission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_missions', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='core.vehicle')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=17)),
                ('altitude', models.FloatField(help_text='Altitude in meters')),
                ('waypoint_type', models.CharField(choices=[('WAYPOINT', 'Waypoint'), ('TAKEOFF', 'Takeoff'), ('LAND', 'Land'), ('RETURN_TO_LAUNCH', 'Return to Launch'), ('LOITER', 'Loiter'), ('LOITER_TIME', 'Loiter Time'), ('LOITER_TURNS', 'Loiter Turns'), ('LOITER_UNLIM', 'Loiter Unlimited')], default='WAYPOINT', max_length=50)),
                ('command', models.IntegerField(default=16, help_text='MAVLink command ID (16=WAYPOINT)')),
                ('param1', models.FloatField(default=0.0, help_text='MAVLink parameter 1')),
                ('param2', models.FloatField(default=0.0, help_text='MAVLink parameter 2')),
                ('param3', models.FloatField(default=0.0, help_text='MAVLink parameter 3')),
                ('param4', models.FloatField(default=0.0, help_text='MAVLink parameter 4')),
                ('speed', models.FloatField(blank=True, help_text='Speed at this waypoint (m/s)', null=True)),
                ('yaw', models.FloatField(blank=True, help_text='Yaw angle at waypoint (degrees)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoint_items', to='core.mission')),
            ],
            options={
                'verbose_name': 'Mission Waypoint',
                'verbose_name_plural': 'Mission Waypoints',
                'ordering': ['mission', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='missionwaypoint',
            index=models.Index(fields=['mission', 'sequence'], name='core_missio_mission_fdb68d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='missionwaypoint',
            unique_together={('mission', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['vehicle', '-created_at'], name='core_missio_vehicle_6a5d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['status'], name='core_missio_status_3a20a8_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['created_by', '-created_at'], name='core_missio_created_ce41c5_idx'),
        ),
    ]
