# Generated by Django 3.2.24 on 2026-04-28 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('timeseries', 'Time series (multiple timesteps)'), ('single', 'Single timestep, multi-product'), ('multiband', 'Single timestep, multi-band')], max_length=20)),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'dataset',
                'verbose_name_plural': 'datasets',
                'ordering': ['site', 'ordering', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text="Stable identifier used in URLs and admin filters, e.g. 'phx_wildfire'.", max_length=80, unique=True)),
                ('name', models.CharField(help_text="Human-readable site name, e.g. 'Phoenix wildfire site'.", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('bounds', models.JSONField(help_text='[west, south, east, north] in WGS84 degrees. Used for fly-to and viewport-intersect filtering.')),
                ('default_zoom', models.PositiveSmallIntegerField(default=15, help_text='Initial zoom level when the user picks this site.')),
                ('default_camera_pitch', models.FloatField(blank=True, help_text='Optional camera pitch in degrees for fly-to (useful for 3D-mesh sites; null for top-down).', null=True)),
                ('ordering', models.PositiveSmallIntegerField(default=0, help_text='Lower values render first in the site picker.')),
                ('is_active', models.BooleanField(default=True, help_text='Hide from frontend without deleting (keeps history).')),
            ],
            options={
                'verbose_name': 'site',
                'verbose_name_plural': 'sites',
                'ordering': ['ordering', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Timestep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="UI label, e.g. '2020-08' or 'Q4 2020'.", max_length=50)),
                ('sort_key', models.CharField(help_text='Sortable key (ISO date is ideal). Used to order the time scrubber.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesteps', to='tile_catalog.dataset')),
            ],
            options={
                'verbose_name': 'timestep',
                'verbose_name_plural': 'timesteps',
                'ordering': ['dataset', 'sort_key'],
                'unique_together': {('dataset', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layer_id', models.CharField(help_text="The tileserver-gl layer id (e.g. 'bf_aug_2020_raster'). Must exist in /data.json for the layer to be usable.", max_length=200, unique=True)),
                ('kind', models.CharField(choices=[('orthophoto', 'Orthophoto / RGB raster'), ('vector', 'Vector features'), ('mesh_3d', '3D mesh / DSM'), ('pca', 'PCA composite / band'), ('rgb_low_zoom', 'RGB at coarse zoom'), ('kmeans', 'Classification (k-means etc.)'), ('polygons', 'Vector polygons'), ('raw', 'Raw point cloud / source data'), ('other', 'Other')], max_length=20)),
                ('label', models.CharField(help_text="Human-friendly label shown in the UI, e.g. 'RGB orthophoto (z15-23)'.", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('default_opacity', models.FloatField(default=0.7, help_text='Initial opacity slider position, 0-1.')),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tile_catalog.dataset')),
                ('timestep', models.ForeignKey(blank=True, help_text='Required for timeseries datasets; must be empty for single/multiband datasets.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tile_catalog.timestep')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['dataset', 'timestep__sort_key', 'ordering', 'kind'],
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='tile_catalog.site'),
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together={('site', 'slug')},
        ),
    ]
